version: "3.8"

services:
  mongo1:
    image: hungnt612/mongo-custom:4.4.18
    container_name: mongo1
    restart: always
    network_mode: host
    command: ["--auth", "--replSet", "my-replica-set", "--bind_ip_all", "--port", "27017", "--keyFile", "/config/mongo-keyfile"]
    volumes:
      - ./data/mongo-1:/data/db
    ports:
      - 27017:27017
    healthcheck:
      test: test $$(echo "rs.initiate({_id:'my-replica-set',members:[{_id:0,host:\"change_this:27017\"},{_id:1,host:\"change_this:27018\"},{_id:2,host:\"change_this:27019\"}]}).ok || rs.status().ok" | mongo --port 27017 --quiet) -eq 1
      interval: 10s
      start_period: 30s

  mongo2:
    image: hungnt612/mongo-custom:4.4.18
    container_name: mongo2
    restart: always
    network_mode: host
    command: ["--auth", "--replSet", "my-replica-set", "--bind_ip_all", "--port", "27018", "--keyFile", "/config/mongo-keyfile"]
    volumes:
      - ./data/mongo-2:/data/db
    ports:
      - 27018:27018

  mongo3:
    image: hungnt612/mongo-custom:4.4.18
    container_name: mongo3
    restart: always
    network_mode: host
    command: ["--auth", "--replSet", "my-replica-set", "--bind_ip_all", "--port", "27019", "--keyFile", "/config/mongo-keyfile"]
    volumes:
      - ./data/mongo-3:/data/db
    ports:
      - 27019:27019